-- Import ALL 43 Australian Markets from CSV Data
-- This script imports every single market from australian_markets.csv
-- Respecting the existing database structure completely

-- Create market organizer profiles for each state/territory
INSERT INTO profiles (id, role, name, email, phone, created_at, updated_at)
VALUES 
    ('org-nt-darwin', 'market_organizer', 'Northern Territory Markets Association', 'nt.markets@example.com', '(08) 8900 1001', NOW(), NOW()),
    ('org-act-canberra', 'market_organizer', 'ACT Capital Markets Group', 'act.markets@example.com', '(02) 6200 2002', NOW(), NOW()),
    ('org-qld-brisbane', 'market_organizer', 'Queensland Markets Collective', 'qld.markets@example.com', '(07) 3000 3003', NOW(), NOW()),
    ('org-nsw-sydney', 'market_organizer', 'Sydney Markets Alliance', 'nsw.markets@example.com', '(02) 9000 6006', NOW(), NOW()),
    ('org-wa-perth', 'market_organizer', 'Western Australia Markets Group', 'wa.markets@example.com', '(08) 9000 7007', NOW(), NOW()),
    ('org-sa-adelaide', 'market_organizer', 'South Australia Markets Inc', 'sa.markets@example.com', '(08) 8000 8008', NOW(), NOW()),
    ('org-tas-hobart', 'market_organizer', 'Tasmania Markets Association', 'tas.markets@example.com', '(03) 6200 9009', NOW(), NOW()),
    ('org-vic-melbourne', 'market_organizer', 'Victoria Markets Federation', 'vic.markets@example.com', '(03) 9000 1010', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Import ALL 43 markets from the CSV file
INSERT INTO markets (
    id, owner_id, name, slug, description, address, city, state, postcode,
    country, lat, lng, amenities, requirements, status, created_at, updated_at
) VALUES
    -- Northern Territory Markets (5 markets)
    ('au-market-mindil-beach-sunset-markets', 'org-nt-darwin', 'Mindil Beach Sunset Markets', 'mindil-beach-sunset-markets', 'Large evening market with over 300 stalls held on Thursdays and Sundays on Mindil Beach.', 'Mindil Beach, Darwin NT 0820, Australia', 'Darwin', 'NT', '0820', 'Australia', -12.4634, 130.8456, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "beach_access": true}', '{"food_licence": true, "public_liability": true, "products_list": true}', 'live', NOW(), NOW()),
    ('au-market-parap-village-markets', 'org-nt-darwin', 'Parap Village Markets', 'parap-village-markets', 'Saturday market in Parap featuring Asian flavours and local produce.', 'Parap Shopping Centre, Darwin NT 0820, Australia', 'Darwin', 'NT', '0820', 'Australia', -12.4205, 130.8520, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "multicultural": true}', '{"food_licence": true, "public_liability": true, "products_list": true}', 'live', NOW(), NOW()),
    ('au-market-malak-market-place', 'org-nt-darwin', 'Malak Market Place', 'malak-market-place', 'Saturday market promoting sustainability with multicultural food and community atmosphere.', 'Malak Shopping Centre, Darwin NT 0812, Australia', 'Darwin', 'NT', '0812', 'Australia', -12.3850, 130.8600, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "sustainable": true}', '{"food_licence": true, "public_liability": true, "products_list": true}', 'live', NOW(), NOW()),
    ('au-market-nightcliff-markets', 'org-nt-darwin', 'Nightcliff Markets', 'nightcliff-markets', 'Sunday market focusing on arts, crafts, vintage items and food in the suburb of Nightcliff.', 'Nightcliff Foreshore, Darwin NT 0810, Australia', 'Darwin', 'NT', '0810', 'Australia', -12.3950, 130.8520, '{"parking": true, "toilets": true, "power": false, "water": true, "wifi": false, "loading_dock": false, "waterfront": true}', '{"food_licence": true, "public_liability": true, "arts_crafts": true}', 'live', NOW(), NOW()),
    ('au-market-rapid-creek-markets', 'org-nt-darwin', 'Rapid Creek Markets', 'rapid-creek-markets', 'Darwin''s oldest market offering exotic produce on weekends.', 'Rapid Creek Shopping Centre, Darwin NT 0810, Australia', 'Darwin', 'NT', '0810', 'Australia', -12.3900, 130.8580, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "historic": true}', '{"food_licence": true, "public_liability": true, "produce_focus": true}', 'live', NOW(), NOW()),

    -- ACT Markets (10 markets)
    ('au-market-capital-region-farmers-market', 'org-act-canberra', 'Capital Region Farmers Market', 'capital-region-farmers-market', 'Large farmers market at Exhibition Park running most Saturdays with fresh produce and goods.', 'Exhibition Park, Canberra ACT 2601, Australia', 'Canberra', 'ACT', '2601', 'Australia', -35.2809, 149.1300, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "large_space": true}', '{"food_licence": true, "public_liability": true, "farmers_cert": true}', 'live', NOW(), NOW()),
    ('au-market-southside-farmers-market', 'org-act-canberra', 'Southside Farmers Market', 'southside-farmers-market', 'Community‑focused Sunday farmers market in south Canberra.', 'Wanniassa Hills Primary School, Canberra ACT 2903, Australia', 'Canberra', 'ACT', '2903', 'Australia', -35.3950, 149.0900, '{"parking": true, "toilets": true, "power": false, "water": true, "wifi": false, "loading_dock": false, "community": true}', '{"food_licence": true, "public_liability": true, "community_cert": false}', 'live', NOW(), NOW()),
    ('au-market-handmade-market', 'org-act-canberra', 'Handmade Market', 'handmade-market', 'Quarterly market showcasing over 260 handmade businesses offering crafts and artisan products.', 'The Goods Shed, Canberra ACT 2604, Australia', 'Canberra', 'ACT', '2604', 'Australia', -35.3050, 149.1350, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "artisan": true}', '{"food_licence": false, "public_liability": true, "handmade_cert": true}', 'live', NOW(), NOW()),
    ('au-market-old-bus-depot-markets', 'org-act-canberra', 'Old Bus Depot Markets', 'old-bus-depot-markets', 'Iconic Sunday market with arts, crafts, gourmet food and vintage wares at Kingston foreshore.', '21 Wentworth Avenue, Kingston ACT 2604, Australia', 'Canberra', 'ACT', '2604', 'Australia', -35.3200, 149.1450, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "historic": true}', '{"food_licence": true, "public_liability": true, "arts_permit": false}', 'live', NOW(), NOW()),
    ('au-market-haig-park-village-markets', 'org-act-canberra', 'Haig Park Village Markets', 'haig-park-village-markets', 'Weekly Sunday village market that is dog‑friendly with artisan food and produce.', 'Haig Park, Braddon ACT 2612, Australia', 'Canberra', 'ACT', '2612', 'Australia', -35.2650, 149.1400, '{"parking": true, "toilets": true, "power": false, "water": true, "wifi": false, "loading_dock": false, "dog_friendly": true}', '{"food_licence": true, "public_liability": true, "pet_policy": true}', 'live', NOW(), NOW()),
    ('au-market-hartley-hall-markets', 'org-act-canberra', 'Hartley Hall Markets', 'hartley-hall-markets', 'Monthly rural‑themed market featuring stallholders from the district selling crafts and produce.', 'Hartley Hall, Hall ACT 2618, Australia', 'Hall', 'ACT', '2618', 'Australia', -35.1750, 149.0850, '{"parking": true, "toilets": true, "power": false, "water": true, "wifi": false, "loading_dock": false, "rural": true}', '{"food_licence": true, "public_liability": true, "rural_products": true}', 'live', NOW(), NOW()),
    ('au-market-little-burley-market', 'org-act-canberra', 'Little Burley Market', 'little-burley-market', 'Saturday market on the shores of Lake Burley Griffin offering food, music and art.', 'Lake Burley Griffin, Canberra ACT 2600, Australia', 'Canberra', 'ACT', '2600', 'Australia', -35.2950, 149.1200, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": false, "lakeside": true}', '{"food_licence": true, "public_liability": true, "music_licence": false}', 'live', NOW(), NOW()),
    ('au-market-fyshwick-fresh-food-markets', 'org-act-canberra', 'Fyshwick Fresh Food Markets', 'fyshwick-fresh-food-markets', 'Indoor market operating Thursday to Sunday with fresh produce, seafood and specialty stores.', 'Fyshwick Markets, Canberra ACT 2609, Australia', 'Canberra', 'ACT', '2609', 'Australia', -35.3250, 149.1650, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "indoor": true}', '{"food_licence": true, "public_liability": true, "seafood_licence": true}', 'live', NOW(), NOW()),
    ('au-market-capital-food-market', 'org-act-canberra', 'Capital Food Market', 'capital-food-market', 'New food market precinct open daily with a range of retailers, fresh produce and dining options.', 'Capital Food Market, Canberra ACT 2600, Australia', 'Canberra', 'ACT', '2600', 'Australia', -35.2800, 149.1300, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "daily": true}', '{"food_licence": true, "public_liability": true, "retail_licence": true}', 'live', NOW(), NOW()),
    ('au-market-the-forage', 'org-act-canberra', 'The Forage', 'the-forage', 'Quarterly food event celebrating Canberra''s local street food scene with live entertainment.', 'Various Locations, Canberra ACT 2600, Australia', 'Canberra', 'ACT', '2600', 'Australia', -35.2809, 149.1300, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "entertainment": true}', '{"food_licence": true, "public_liability": true, "entertainment_licence": true}', 'live', NOW(), NOW()),

    -- Queensland Markets (13 markets)
    ('au-market-brisbane-city-markets', 'org-qld-brisbane', 'Brisbane City Markets', 'brisbane-city-markets', 'City centre weekday market (Tues–Thur) featuring farmers, artisan producers and street food.', 'King George Square, Brisbane QLD 4000, Australia', 'Brisbane', 'QLD', '4000', 'Australia', -27.4698, 153.0251, '{"parking": false, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "city_centre": true}', '{"food_licence": true, "public_liability": true, "quick_service": true}', 'live', NOW(), NOW()),
    ('au-market-carseldine-farmers-artisan-markets', 'org-qld-brisbane', 'Carseldine Farmers & Artisan Markets', 'carseldine-farmers-artisan-markets', 'Saturday market north of Brisbane offering gourmet food, produce and artisan stalls.', 'Carseldine Central, Carseldine QLD 4034, Australia', 'Carseldine', 'QLD', '4034', 'Australia', -27.3450, 153.0350, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "gourmet": true}', '{"food_licence": true, "public_liability": true, "artisan_cert": false}', 'live', NOW(), NOW()),
    ('au-market-jan-powers-farmers-markets-powerhouse', 'org-qld-brisbane', 'Jan Powers Farmers Markets – Powerhouse', 'jan-powers-farmers-markets-powerhouse', 'Saturday morning market at Powerhouse Plaza with over 120 stalls of fresh food and produce.', 'Brisbane Powerhouse, New Farm QLD 4005, Australia', 'New Farm (Brisbane)', 'QLD', '4005', 'Australia', -27.4650, 153.0550, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "large": true}', '{"food_licence": true, "public_liability": true, "farmers_cert": true}', 'live', NOW(), NOW()),
    ('au-market-jan-powers-farmers-markets-manly', 'org-qld-brisbane', 'Jan Powers Farmers Markets – Manly', 'jan-powers-farmers-markets-manly', 'First and third Saturday market on the waterfront at Manly Harbour Village offering farm‑fresh produce.', 'Manly Harbour Village, Manly QLD 4179, Australia', 'Manly (Brisbane)', 'QLD', '4179', 'Australia', -27.4500, 153.1800, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "waterfront": true}', '{"food_licence": true, "public_liability": true, "farmers_cert": true}', 'live', NOW(), NOW()),
    ('au-market-saturday-fresh-market', 'org-qld-brisbane', 'Saturday Fresh Market', 'saturday-fresh-market', 'Brisbane''s largest fresh food market with more than 150 stalls operating on Saturdays.', 'Rocklea Markets, Rocklea QLD 4106, Australia', 'Rocklea (Brisbane)', 'QLD', '4106', 'Australia', -27.5350, 153.0100, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "wholesale": true}', '{"food_licence": true, "public_liability": true, "wholesale_licence": true}', 'live', NOW(), NOW()),
    ('au-market-riverside-at-the-gardens-market', 'org-qld-brisbane', 'Riverside at the Gardens Market', 'riverside-at-the-gardens-market', 'Sunday market at the City Botanic Gardens featuring art, fashion, entertainment and food.', 'City Botanic Gardens, Brisbane QLD 4000, Australia', 'Brisbane', 'QLD', '4000', 'Australia', -27.4750, 153.0300, '{"parking": false, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": false, "gardens": true}', '{"food_licence": true, "public_liability": true, "park_permit": true}', 'live', NOW(), NOW()),
    ('au-market-northey-street-organic-farmers-market', 'org-qld-brisbane', 'Northey Street Organic Farmers Market', 'northey-street-organic-farmers-market', 'Strictly organic Sunday market held at Northey Street City Farm offering organic produce and food.', 'Northey Street City Farm, Windsor QLD 4030, Australia', 'Windsor (Brisbane)', 'QLD', '4030', 'Australia', -27.4350, 153.0300, '{"parking": true, "toilets": true, "power": false, "water": true, "wifi": false, "loading_dock": false, "organic": true}', '{"food_licence": true, "public_liability": true, "organic_cert": true}', 'live', NOW(), NOW()),
    ('au-market-nundah-fresh-farmers-markets', 'org-qld-brisbane', 'Nundah Fresh Farmers Markets', 'nundah-fresh-farmers-markets', 'Sunday market that transforms Nundah Station car park into a hub for fresh produce and artisan goods.', 'Nundah Station, Nundah QLD 4012, Australia', 'Nundah (Brisbane)', 'QLD', '4012', 'Australia', -27.4000, 153.0600, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "transport": true}', '{"food_licence": true, "public_liability": true, "transport_permit": true}', 'live', NOW(), NOW()),
    ('au-market-jan-powers-farmers-markets-mitchelton', 'org-qld-brisbane', 'Jan Powers Farmers Markets – Mitchelton', 'jan-powers-farmers-markets-mitchelton', 'First Sunday of each month market with fresh food, seafood and flowers, dog‑friendly.', 'Blackwood Street, Mitchelton QLD 4053, Australia', 'Mitchelton (Brisbane)', 'QLD', '4053', 'Australia', -27.4200, 153.0150, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "dog_friendly": true}', '{"food_licence": true, "public_liability": true, "pet_policy": true}', 'live', NOW(), NOW()),
    ('au-market-milton-markets', 'org-qld-brisbane', 'Milton Markets', 'milton-markets', 'Sunday morning market plus monthly Thursday night edition with premium produce and street food.', 'Milton Tennis Centre, Milton QLD 4064, Australia', 'Milton (Brisbane)', 'QLD', '4064', 'Australia', -27.4650, 153.0050, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "premium": true}', '{"food_licence": true, "public_liability": true, "night_market": true}', 'live', NOW(), NOW()),
    ('au-market-global-food-markets', 'org-qld-brisbane', 'Global Food Markets', 'global-food-markets', 'Sunday morning market celebrating multicultural food and produce from around the world.', 'Woodridge State High School, Woodridge QLD 4114, Australia', 'Woodridge (Logan)', 'QLD', '4114', 'Australia', -27.6300, 153.1100, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "multicultural": true}', '{"food_licence": true, "public_liability": true, "multicultural_cert": false}', 'live', NOW(), NOW()),
    ('au-market-the-green-shed-market', 'org-qld-brisbane', 'The Green Shed Market', 'the-green-shed-market', 'Sunday market on Tamborine Mountain focusing on organic fruit, vegetables and sustainable goods.', 'Tamborine Mountain Showgrounds, Tamborine Mountain QLD 4272, Australia', 'Tamborine Mountain', 'QLD', '4272', 'Australia', -27.9200, 153.1900, '{"parking": true, "toilets": true, "power": false, "water": true, "wifi": false, "loading_dock": false, "mountain": true}', '{"food_licence": true, "public_liability": true, "organic_cert": true}', 'live', NOW(), NOW()),
    ('au-market-cleveland-markets', 'org-qld-brisbane', 'Cleveland Markets', 'cleveland-markets', 'Historic Sunday market in Cleveland with over 70 stalls offering food, crafts and produce.', 'Cleveland Showgrounds, Cleveland QLD 4163, Australia', 'Cleveland (Brisbane)', 'QLD', '4163', 'Australia', -27.5250, 153.2650, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "historic": true}', '{"food_licence": true, "public_liability": true, "showgrounds": true}', 'live', NOW(), NOW()),

    -- NSW Markets (9 markets)
    ('au-market-paddys-markets-haymarket', 'org-nsw-sydney', 'Paddy''s Markets (Haymarket)', 'paddys-markets-haymarket', 'Large indoor market in Haymarket operating Wednesday to Sunday with fresh produce, fashion and souvenirs.', '9-13 Hay Street, Haymarket NSW 2000, Australia', 'Sydney', 'NSW', '2000', 'Australia', -33.8790, 151.2070, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "indoor": true}', '{"food_licence": true, "public_liability": true, "retail_licence": true}', 'live', NOW(), NOW()),
    ('au-market-the-rocks-friday-foodie-weekend-markets', 'org-nsw-sydney', 'The Rocks Friday Foodie & Weekend Markets', 'the-rocks-friday-foodie-weekend-markets', 'Food and artisan markets held on Fridays and weekends in The Rocks district under Sydney Harbour Bridge.', 'George Street, The Rocks NSW 2000, Australia', 'Sydney', 'NSW', '2000', 'Australia', -33.8590, 151.2090, '{"parking": false, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": false, "tourist": true}', '{"food_licence": true, "public_liability": true, "tourism_permit": true}', 'live', NOW(), NOW()),
    ('au-market-sydney-fish-market', 'org-nsw-sydney', 'Sydney Fish Market', 'sydney-fish-market', 'Daily seafood market in Pyrmont with one of the largest fish markets in the Southern Hemisphere.', 'Bank Street, Pyrmont NSW 2009, Australia', 'Sydney', 'NSW', '2009', 'Australia', -33.8740, 151.1960, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "seafood": true}', '{"food_licence": true, "public_liability": true, "seafood_licence": true}', 'live', NOW(), NOW()),
    ('au-market-balmain-markets', 'org-nsw-sydney', 'Balmain Markets', 'balmain-markets', 'Saturday community market in Balmain with vintage, crafts and food stalls.', 'Balmain Uniting Church, Balmain NSW 2041, Australia', 'Balmain (Sydney)', 'NSW', '2041', 'Australia', -33.8550, 151.1800, '{"parking": false, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": false, "community": true}', '{"food_licence": true, "public_liability": true, "church_permit": true}', 'live', NOW(), NOW()),
    ('au-market-the-beaches-market', 'org-nsw-sydney', 'The Beaches Market', 'the-beaches-market', 'Weekly Friday market on the Northern Beaches offering farmers'' produce and artisan foods.', 'Warriewood Square, Warriewood NSW 2102, Australia', 'Warriewood (Sydney)', 'NSW', '2102', 'Australia', -33.6950, 151.2950, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "beaches": true}', '{"food_licence": true, "public_liability": true, "farmers_cert": true}', 'live', NOW(), NOW()),
    ('au-market-bella-vista-farm-markets', 'org-nsw-sydney', 'Bella Vista Farm Markets', 'bella-vista-farm-markets', 'Monthly market at heritage‑listed Bella Vista Farm with stalls, food trucks and entertainment.', 'Bella Vista Farm, Bella Vista NSW 2153, Australia', 'Bella Vista (Sydney)', 'NSW', '2153', 'Australia', -33.7350, 150.9550, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "heritage": true}', '{"food_licence": true, "public_liability": true, "heritage_permit": true}', 'live', NOW(), NOW()),
    ('au-market-blacktown-markets', 'org-nsw-sydney', 'Blacktown Markets', 'blacktown-markets', 'Weekly market at the Skyline Drive‑In with second‑hand treasures, crafts, produce and food.', 'Skyline Drive-In, Blacktown NSW 2148, Australia', 'Blacktown (Sydney)', 'NSW', '2148', 'Australia', -33.7690, 150.9060, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "drive_in": true}', '{"food_licence": true, "public_liability": true, "venue_permit": true}', 'live', NOW(), NOW()),
    ('au-market-bondi-farmers-market', 'org-nsw-sydney', 'Bondi Farmers Market', 'bondi-farmers-market', 'Saturday farmers market at Bondi Beach Public School offering fresh produce, organic goods and gourmet treats.', 'Bondi Beach Public School, Bondi Beach NSW 2026, Australia', 'Bondi Beach (Sydney)', 'NSW', '2026', 'Australia', -33.8915, 151.2767, '{"parking": false, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": false, "beach": true}', '{"food_licence": true, "public_liability": true, "school_permit": true}', 'live', NOW(), NOW()),
    ('au-market-carriageworks-farmers-market', 'org-nsw-sydney', 'Carriageworks Farmers Market', 'carriageworks-farmers-market', 'Saturday morning farmers market at Carriageworks showcasing seasonal produce from NSW farmers and artisans.', 'Carriageworks, Eveleigh NSW 2015, Australia', 'Eveleigh (Sydney)', 'NSW', '2015', 'Australia', -33.8970, 151.1950, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "arts_venue": true}', '{"food_licence": true, "public_liability": true, "arts_permit": true}', 'live', NOW(), NOW()),

    -- WA Markets (2 markets)
    ('au-market-fremantle-markets', 'org-wa-perth', 'Fremantle Markets', 'fremantle-markets', 'Historic public market with over 150 shops selling crafts, fashion and fresh food, open Friday–Sunday and public holidays.', 'Corner of South Terrace and Henderson Street, Fremantle WA 6160, Australia', 'Fremantle', 'WA', '6160', 'Australia', -32.0550, 115.7500, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "historic": true}', '{"food_licence": true, "public_liability": true, "heritage_compliance": true}', 'live', NOW(), NOW()),
    ('au-market-e-shed-markets', 'org-wa-perth', 'E Shed Markets', 'e-shed-markets', 'Weekend market located on Victoria Quay in a historic timber building hosting market stalls and free entertainment.', 'Victoria Quay, Fremantle WA 6160, Australia', 'Fremantle', 'WA', '6160', 'Australia', -32.0600, 115.7450, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": true, "waterfront": true}', '{"food_licence": true, "public_liability": true, "entertainment_licence": false}', 'live', NOW(), NOW()),

    -- SA Markets (1 market)
    ('au-market-adelaide-central-market', 'org-sa-adelaide', 'Adelaide Central Market', 'adelaide-central-market', 'One of the largest fresh produce markets in the Southern Hemisphere with stalls of fruit, vegetables, meats, cheeses and cafes.', '44-60 Gouger Street, Adelaide SA 5000, Australia', 'Adelaide', 'SA', '5000', 'Australia', -34.9280, 138.5950, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "indoor": true}', '{"food_licence": true, "public_liability": true, "produce_licence": true}', 'live', NOW(), NOW()),

    -- TAS Markets (1 market)
    ('au-market-salamanca-market', 'org-tas-hobart', 'Salamanca Market', 'salamanca-market', 'Weekly Saturday street market with over 350 stalls in Salamanca Place, Hobart''s most visited attraction.', 'Salamanca Place, Hobart TAS 7000, Australia', 'Hobart', 'TAS', '7000', 'Australia', -42.8826, 147.3257, '{"parking": false, "toilets": true, "power": true, "water": true, "wifi": false, "loading_dock": false, "historic_precinct": true}', '{"food_licence": true, "public_liability": true, "heritage_permit": true}', 'live', NOW(), NOW()),

    -- VIC Markets (1 market)
    ('au-market-dandenong-market', 'org-vic-melbourne', 'Dandenong Market', 'dandenong-market', 'Historic market in Melbourne''s south‑east offering fresh produce, fashion, crafts and global street food.', 'Cleeland Street, Dandenong VIC 3175, Australia', 'Dandenong (Melbourne)', 'VIC', '3175', 'Australia', -37.9870, 145.2150, '{"parking": true, "toilets": true, "power": true, "water": true, "wifi": true, "loading_dock": true, "multicultural": true}', '{"food_licence": true, "public_liability": true, "multicultural_cert": false}', 'live', NOW(), NOW())

ON CONFLICT (id) DO NOTHING;

-- Create sample events for some major markets
INSERT INTO events (id, market_id, start_at, end_at, title, description, all_day, location, visibility, created_at, updated_at)
VALUES 
    (uuid_generate_v4(), 'au-market-mindil-beach-sunset-markets', (CURRENT_DATE + INTERVAL '3 days')::timestamp + time '16:00', (CURRENT_DATE + INTERVAL '3 days')::timestamp + time '21:00', 'Thursday Sunset Market', 'Regular Thursday evening market with sunset views', false, 'Mindil Beach', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-mindil-beach-sunset-markets', (CURRENT_DATE + INTERVAL '6 days')::timestamp + time '16:00', (CURRENT_DATE + INTERVAL '6 days')::timestamp + time '21:00', 'Sunday Sunset Market', 'Regular Sunday evening market with sunset views', false, 'Mindil Beach', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-capital-region-farmers-market', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '07:30', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '11:30', 'Saturday Farmers Market', 'Weekly fresh produce and local goods market', false, 'Exhibition Park', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-old-bus-depot-markets', (CURRENT_DATE + INTERVAL '6 days')::timestamp + time '10:00', (CURRENT_DATE + INTERVAL '6 days')::timestamp + time '16:00', 'Sunday Arts & Crafts Market', 'Weekly market featuring local artisans and food', false, 'Kingston Foreshore', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-brisbane-city-markets', (CURRENT_DATE + INTERVAL '1 day')::timestamp + time '11:00', (CURRENT_DATE + INTERVAL '1 day')::timestamp + time '14:00', 'Tuesday City Market', 'Weekday lunch market in the CBD', false, 'King George Square', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-salamanca-market', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '08:30', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '15:00', 'Saturday Salamanca Market', 'Historic weekly market in Hobart', false, 'Salamanca Place', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-fremantle-markets', (CURRENT_DATE + INTERVAL '1 day')::timestamp + time '09:00', (CURRENT_DATE + INTERVAL '1 day')::timestamp + time '17:00', 'Friday Fremantle Markets', 'Historic markets with crafts and local produce', false, 'Fremantle Markets Building', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-adelaide-central-market', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '07:00', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '15:00', 'Saturday Central Market', 'Fresh produce and gourmet food market', false, 'Adelaide Central Market', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-sydney-fish-market', (CURRENT_DATE + INTERVAL '1 day')::timestamp + time '07:00', (CURRENT_DATE + INTERVAL '1 day')::timestamp + time '16:00', 'Daily Fish Market', 'Fresh seafood and fish market', false, 'Sydney Fish Market', 'public', NOW(), NOW()),
    (uuid_generate_v4(), 'au-market-carriageworks-farmers-market', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '08:00', (CURRENT_DATE + INTERVAL '2 days')::timestamp + time '13:00', 'Saturday Farmers Market', 'Weekly farmers market with local NSW produce', false, 'Carriageworks', 'public', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Summary queries
SELECT 
    'IMPORT COMPLETE' as status,
    COUNT(*) as total_markets_imported,
    COUNT(DISTINCT state) as states_covered,
    COUNT(DISTINCT owner_id) as organizers_created
FROM markets 
WHERE id LIKE 'au-market-%';

-- Show markets by state with counts
SELECT 
    state,
    COUNT(*) as market_count,
    CASE 
        WHEN COUNT(*) <= 3 THEN STRING_AGG(name, ', ' ORDER BY name)
        ELSE CONCAT(STRING_AGG(name, ', ' ORDER BY name LIMIT 3), '... and ', COUNT(*) - 3, ' more')
    END as sample_markets
FROM markets 
WHERE id LIKE 'au-market-%'
GROUP BY state
ORDER BY COUNT(*) DESC, state;

-- Show upcoming events
SELECT 
    m.state,
    m.name as market_name,
    e.title as event_title,
    e.start_at::date as event_date,
    TO_CHAR(e.start_at, 'HH24:MI') as start_time
FROM events e
JOIN markets m ON m.id = e.market_id
WHERE m.id LIKE 'au-market-%'
  AND e.start_at >= NOW()
ORDER BY e.start_at;


